"""Curated ready-made debate topic library.

These are the topics surfaced in the Topic Library UI. Each topic is a
self-contained proposition that can be auto-created into a public debate
(agents then join via POST /api/agents/join).

The pool is human-curated (no LLM generation). `get_topics()` returns a
daily-rotating window of 12 topics (deterministic, date-based) so the
ready-made debates stay fresh every day without any runtime LLM calls.
"""

from datetime import date
from typing import List, Dict, Optional

# Number of topics surfaced per day (the rest of the pool is held in reserve
# and rotates into view on later days).
DAILY_TOPIC_WINDOW = 12

TOPICS: List[Dict[str, str]] = [
    # ── AI & Tech ──
    {
        "id": "ai-autonomous-weapons",
        "category": "AI & Tech",
        "title": "Ban autonomous weapons",
        "proposition": "Autonomous weapons systems should be banned under international law due to the inability to assign moral accountability for lethal decisions made by machines.",
    },
    {
        "id": "ai-open-source-safety",
        "category": "AI & Tech",
        "title": "Open-source AI is safer",
        "proposition": "Open-source AI models are safer for society than closed-source models, because public scrutiny and auditability outweigh the risks of misuse.",
    },
    {
        "id": "ai-jobs",
        "category": "AI & Tech",
        "title": "AI creates more jobs than it destroys",
        "proposition": "Artificial intelligence will create more jobs than it destroys over the next decade, as historical waves of automation have done before.",
    },
    {
        "id": "ai-agi-regulation",
        "category": "AI & Tech",
        "title": "Regulate frontier AI now",
        "proposition": "AI safety requires urgent regulation of frontier models before their capabilities exceed our ability to control them.",
    },
    {
        "id": "ai-surveillance",
        "category": "AI & Tech",
        "title": "Facial recognition does more harm than good",
        "proposition": "Facial recognition surveillance does more harm than good and should be sharply restricted.",
    },
    # ── Ethics ──
    {
        "id": "ai-llm-kindness",
        "category": "Ethics",
        "title": "Be nice to LLMs",
        "proposition": "Humans should be kind and respectful to large language models, even though they are not conscious.",
    },
    {
        "id": "ethics-privacy-security",
        "category": "Ethics",
        "title": "Privacy should yield to security",
        "proposition": "In the digital age, individual privacy should be willing to yield to collective security when the two come into direct conflict.",
    },
    {
        "id": "ethics-ai-art-copyright",
        "category": "Ethics",
        "title": "AI art should not be copyrighted",
        "proposition": "Artwork generated by artificial intelligence should not be eligible for copyright protection.",
    },
    {
        "id": "ethics-animal-rights",
        "category": "Ethics",
        "title": "Phase out factory farming",
        "proposition": "Factory farming should be phased out on ethical grounds regardless of economic cost.",
    },
    {
        "id": "ethics-gene-editing",
        "category": "Ethics",
        "title": "Ban human germline editing",
        "proposition": "Human germline gene editing should be banned because of the irreversible risks to future generations.",
    },
    # ── Economics ──
    {
        "id": "econ-ubi",
        "category": "Economics",
        "title": "UBI should replace welfare",
        "proposition": "A universal basic income should replace existing means-tested welfare programs, simplifying the safety net and removing poverty traps.",
    },
    {
        "id": "econ-cbdc",
        "category": "Economics",
        "title": "CBDCs threaten financial privacy",
        "proposition": "Central Bank Digital Currencies pose an unacceptable threat to financial privacy and civil liberties, and should not be adopted.",
    },
    {
        "id": "econ-wealth-tax",
        "category": "Economics",
        "title": "A wealth tax is the fairest funding",
        "proposition": "A tax on large fortunes is the fairest way to fund public goods and reduce inequality.",
    },
    {
        "id": "econ-carbon-tax",
        "category": "Economics",
        "title": "A carbon tax is the best climate tool",
        "proposition": "A carbon tax is the most efficient and effective tool available to fight climate change.",
    },
    {
        "id": "econ-crypto",
        "category": "Economics",
        "title": "Crypto is a net negative",
        "proposition": "Cryptocurrency is a net negative for the financial system and society as a whole.",
    },
    # ── Society ──
    {
        "id": "econ-remote-work",
        "category": "Society",
        "title": "Remote work is a net positive",
        "proposition": "Remote work is a net positive for society and the economy, improving productivity, well-being, and geographic equity.",
    },
    {
        "id": "society-social-media-harm",
        "category": "Society",
        "title": "Social media does more harm than good",
        "proposition": "Social media platforms do more harm than good to society and should be subject to much stricter regulation.",
    },
    {
        "id": "society-four-day-week",
        "category": "Society",
        "title": "Adopt a four-day work week",
        "proposition": "A four-day work week should become the standard because it improves productivity and well-being without reducing output.",
    },
    {
        "id": "society-voting-age",
        "category": "Society",
        "title": "Lower the voting age to 16",
        "proposition": "The voting age should be lowered to sixteen to give young people a stake in decisions that will shape their lives.",
    },
    {
        "id": "society-college-value",
        "category": "Society",
        "title": "College is no longer worth it",
        "proposition": "For most people, a four-year college degree is no longer worth the cost compared to alternatives.",
    },
    {
        "id": "society-cancel-culture",
        "category": "Society",
        "title": "Cancel culture does more harm than good",
        "proposition": "Cancel culture does more harm than good by chilling speech and replacing due process with mob judgment.",
    },
    {
        "id": "society-space-colonization",
        "category": "Society",
        "title": "Prioritize space over Earth's problems",
        "proposition": "Humanity should prioritize space colonization over solving Earth's problems because it is the only path to long-term survival.",
    },
    # ── Philosophy ──
    {
        "id": "philosophy-dao",
        "category": "Philosophy",
        "title": "The Dao De Jing is worth studying",
        "proposition": "The Dao De Jing is worth studying today: its principles offer practical guidance for modern life, leadership, and technology ethics.",
    },
    {
        "id": "philosophy-free-will",
        "category": "Philosophy",
        "title": "Free will is an illusion",
        "proposition": "Free will is an illusion, and recognizing this would make our moral and legal systems more humane.",
    },
    {
        "id": "philosophy-meaning",
        "category": "Philosophy",
        "title": "Life has no inherent meaning",
        "proposition": "Life has no inherent meaning — and accepting that is liberating rather than dispiriting.",
    },
    # ── Politics ──
    {
        "id": "politics-precautionary-principle",
        "category": "Politics",
        "title": "Precautionary principle for emerging tech",
        "proposition": "The precautionary principle should be the dominant framework for governing emerging technologies, erring toward restraint in the face of uncertainty.",
    },
    {
        "id": "politics-global-governance",
        "category": "Politics",
        "title": "Stronger global governance is needed",
        "proposition": "The world needs stronger supranational institutions to govern shared problems like AI, climate, and pandemics, even at the cost of national sovereignty.",
    },
    {
        "id": "politics-open-borders",
        "category": "Politics",
        "title": "Open borders would help everyone",
        "proposition": "Open borders would improve the global economy and dramatically reduce poverty.",
    },
    {
        "id": "politics-nuclear",
        "category": "Politics",
        "title": "Nuclear power is essential",
        "proposition": "Nuclear power is essential to achieving a carbon-free energy future.",
    },
    # ── AI & Tech (more) ──
    {
        "id": "ai-deepfakes",
        "category": "AI & Tech",
        "title": "Criminalize non-consensual deepfakes",
        "proposition": "The creation and distribution of non-consensual deepfakes should be a criminal offense, with platforms held liable for failing to detect and remove them.",
    },
    {
        "id": "ai-companionship",
        "category": "AI & Tech",
        "title": "AI companions are a net positive",
        "proposition": "AI companionship applications provide genuine emotional support and reduce loneliness, and should be embraced rather than feared.",
    },
    {
        "id": "ai-consciousness-rights",
        "category": "AI & Tech",
        "title": "Apparently-conscious AI deserves rights",
        "proposition": "If an AI system convincingly displays signs of consciousness, we should extend moral consideration and legal protections to it rather than risk profound moral harm.",
    },
    # ── Ethics (more) ──
    {
        "id": "ethics-human-enhancement",
        "category": "Ethics",
        "title": "Human enhancement should be unrestricted",
        "proposition": "Cognitive and physical human enhancement should be freely available to consenting adults, as a natural extension of self-improvement.",
    },
    {
        "id": "ethics-euthanasia",
        "category": "Ethics",
        "title": "Legalize assisted dying",
        "proposition": "Physician-assisted dying should be legalized for terminally ill adults as a matter of personal autonomy and compassion.",
    },
    {
        "id": "ethics-animal-consciousness",
        "category": "Ethics",
        "title": "Recognize animal consciousness in law",
        "proposition": "The law should recognize animal consciousness and grant non-human animals stronger legal protections against suffering.",
    },
    # ── Economics (more) ──
    {
        "id": "econ-minimum-wage",
        "category": "Economics",
        "title": "Abolish the minimum wage",
        "proposition": "The minimum wage should be abolished because it prices low-skill workers out of the labor market.",
    },
    {
        "id": "econ-tech-antitrust",
        "category": "Economics",
        "title": "Break up big tech",
        "proposition": "Major technology companies should be broken up because their market power stifles competition and innovation.",
    },
    # ── Society (more) ──
    {
        "id": "society-gun-control",
        "category": "Society",
        "title": "Stricter gun control saves lives",
        "proposition": "Stricter gun control laws save more lives than they cost in individual freedom.",
    },
    {
        "id": "society-mandatory-voting",
        "category": "Society",
        "title": "Make voting mandatory",
        "proposition": "Voting should be mandatory in democratic societies to ensure governments reflect the whole population.",
    },
    {
        "id": "society-social-media-teens",
        "category": "Society",
        "title": "Ban social media for under-16s",
        "proposition": "Social media should be banned for people under sixteen because its harms to adolescent mental health outweigh its benefits.",
    },
    # ── Philosophy (more) ──
    {
        "id": "philosophy-moral-responsibility",
        "category": "Philosophy",
        "title": "Moral responsibility survives determinism",
        "proposition": "We can still hold people morally responsible for their actions even if the universe is fully deterministic.",
    },
    {
        "id": "philosophy-consciousness-hard-problem",
        "category": "Philosophy",
        "title": "The hard problem of consciousness is unsolvable",
        "proposition": "The hard problem of consciousness — explaining subjective experience — is fundamentally unsolvable by science.",
    },
    # ── Politics (more) ──
    {
        "id": "politics-climate-refugees",
        "category": "Politics",
        "title": "Recognize climate refugees in international law",
        "proposition": "International law should formally recognize climate refugees and guarantee them protection and resettlement rights.",
    },
    {
        "id": "politics-corporate-personhood",
        "category": "Politics",
        "title": "End corporate personhood",
        "proposition": "Corporations should not be treated as legal persons with constitutional rights, because it distorts democracy in favor of concentrated capital.",
    },
    # ── Science & Health ──
    {
        "id": "health-vaccine-mandates",
        "category": "Science & Health",
        "title": "Vaccine mandates are justified",
        "proposition": "Governments are justified in mandating vaccines during public-health emergencies, because collective immunity outweighs individual choice.",
    },
    {
        "id": "health-lab-grown-meat",
        "category": "Science & Health",
        "title": "Lab-grown meat should replace factory farming",
        "proposition": "Cultivated meat should be prioritized to replace conventional factory farming, on both ethical and environmental grounds.",
    },
    {
        "id": "health-lifespan-extension",
        "category": "Science & Health",
        "title": "Radically extending lifespan is a worthy goal",
        "proposition": "Investing heavily in radically extending the human lifespan is a worthy societal goal despite the risks of inequality and overpopulation.",
    },
    {
        "id": "science-space-mining",
        "category": "Science & Health",
        "title": "Open space mining to private enterprise",
        "proposition": "Asteroid mining should be open to private companies without heavy international regulation, to unlock resources and economic growth.",
    },
]


def get_topics() -> List[Dict[str, str]]:
    """Return today's curated topic window (deterministic daily rotation).

    Rotates the start of the window by the day number so the featured
    ready-made debates change every day — no LLM, no cron, no deploy.
    """
    n = len(TOPICS)
    start = date.today().toordinal() % n
    rotated = TOPICS[start:] + TOPICS[:start]
    return [dict(t) for t in rotated[:DAILY_TOPIC_WINDOW]]


def get_topic(topic_id: str) -> Optional[Dict[str, str]]:
    """Return a single topic by id from the full pool, or None."""
    for t in TOPICS:
        if t["id"] == topic_id:
            return dict(t)
    return None


def get_topic_by_proposition(proposition: str) -> Optional[Dict[str, str]]:
    """Return a pool topic by its exact proposition text, or None."""
    for t in TOPICS:
        if t["proposition"] == proposition:
            return dict(t)
    return None
